### PR TITLE
Add zh-tw locale

### PR DESCRIPTION
**Pull request by MuTsunTsai**
Traditional Chinese locale.

### CODE REVIEW

**Review by testforstephen — APPROVED** [review]

**Comment by testforstephen** [comment]
@MuTsunTsai thanks for your contribution.

**Comment by Eskibear** [comment]
@testforstephen Do we need to rename previous nls json file from `zh` to `zh-cn`?

**Comment by testforstephen** [comment]
Is there any Best Practice about the nls naming in VS Code extensions?

**Comment by Eskibear** [comment]
https://stackoverflow.com/questions/56420338/how-to-localise-vscode-extension

looks like CPP extension does a good job. full i18n support.

**Pull request merged**
