### PR TITLE
Changes that will allow an array of envFile locations to be defined

### PR DESCRIPTION
**Pull request by hildo**
Changes for issue #1505

### CODE REVIEW

**Comment by hildo** [comment]
Is there something I can do to help here?  I don't understand why my changes would be causing these failures?  It looks like it is related to this step?
image

**Comment by hildo** [comment]
It looks like the tool being used (vsce) needs NodeJS minimum version 20, and the build pipeline is using version 16?
image
Should Node be upgraded?

**Comment by hildo** [comment]
@jdneo @testforstephen I have attempted to update the CI build to use NodeJS version 20, with the hope that the build issues will be addressed.  Could someone please approve the workflow so we can see if the changes were sufficient?  If I understand correctly, the workflow approval is not Pull Request approval, and just running the pipeline against this feature branch.

**Comment by testforstephen** [comment]
please also update the envFile's type definition (should be `["array", "string"]`) in package.json and description in package.nls.json

https://github.com/microsoft/vscode-java-debug/blob/4a903c4c3c43e3072dc5381cd224170f37799631/package.json#L488-L489

And 
https://github.com/microsoft/vscode-java-debug/blob/4a903c4c3c43e3072dc5381cd224170f37799631/package.nls.json#L21

**Comment by hildo** [comment]
Of course.  Thank you for the review.  Please let me know if I have done them correctly  (I am not 100% sure that my changes to package.json are correct).

**Review by testforstephen — APPROVED** [review]

**Comment by hildo** [comment]
Thank you!

**Pull request merged**
